# arrange() 生成等差数列

根据 start 与 stop 指定的范围以及 step 设定的步长，生成一个 ndarray。

<b>numpy.arange(start, stop, step, dtype)</b>

参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | start| 起始值，默认为0   |
| 2   | stop | 终止值（不包含）        |
| 3      | step | 步长，默认为1        |
| 4      | dtype |  返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。  

In [2]:
import numpy as np

In [3]:
np.arange(10) # 只有一个参数就是stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10,2)# 指定步长为2

array([1, 3, 5, 7, 9])

In [14]:
np.arange(10,step=2)# 使用关键字传参来指定step

array([0, 2, 4, 6, 8])

In [9]:
np.arange(4.5)# 步长默认是1，下面的结果表示浮点数0.0,1.0

array([0., 1., 2., 3., 4.])

In [12]:
np.arange(5,dtype= float)

array([0., 1., 2., 3., 4.])

In [10]:
np.arange(3,4.5,0.3) # 三个参数都可以是浮点型

array([3. , 3.3, 3.6, 3.9, 4.2])

---

# linspace() 创建等差数列

返回在间隔[开始，停止]上计算的num个均匀间隔的样本。<b>数组是一个等差数列构成</b>

<b>np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)</b>

参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | start| 必填项，序列的起始值，  |
| 2   | stop | 必填项，序列的终止值，如果endpoint为true，该值包含于数列中      |
| 3      | num | 要生成的等步长的样本数量，默认为50      |
| 4      | endpoint |  该值为 true 时，数列中包含stop值，反之不包含，默认是True。  | 
| 5      | retstep |  如果为 True 时，生成的数组中会显示间距，反之不显示。   | 
| 6      | dtype |  ndarray 的数据类型 | 

In [8]:
# 从1-10，包含边界在内等分的10个值. 值的类型默认为浮点型
a=np.linspace(1,10,10)
print(a)
print(type(a))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [13]:
a=np.linspace(1,10,10,dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
a=np.linspace(1,10,9,retstep=True)
print(a) # 最后的结果是元组
print(a[0])
print(type(a[0])) 

(array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ]), 1.125)
[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
<class 'numpy.ndarray'>


#  等比数列

返回在间隔[开始，停止]上计算的num个均匀间隔的样本。<b>数组是一个等比数列构成</b>

<b>np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)</b>

参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | start| 必填项，序列的起始值，  |
| 2   | stop | 必填项，序列的终止值，如果endpoint为true，该值包含于数列中      |
| 3      | num | 要生成的等步长的样本数量，默认为50      |
| 4      | endpoint |  该值为 true 时，数列中包含stop值，反之不包含，默认是True。  | 
| 5      | base |  对数 log 的底数   | 
| 6      | dtype |  ndarray 的数据类型 | 

In [27]:
np.logspace(0,3,4) # 默认的底数是10 起始值为10的零次方

array([   1.,   10.,  100., 1000.])

In [28]:
np.logspace(1,3,3,base=2)# base需要使用关键字传参（如果前面没有传递的话）

array([2., 4., 8.])

In [29]:
 np.logspace(1,3,4,base=2 # 此时的公比就不是2

array([2.       , 3.1748021, 5.0396842, 8.       ])

#  全0数列

创建指定大小的数组，数组元素以 0 来填充

<b>numpy.zeros(shape, dtype = float, order = 'C')</b>

参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | shape| 数组形状  |
| 2   | dtype | 数据类型，可选     |

In [30]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [35]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [37]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [38]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [41]:
np.zeros((2,2,3))# 三维 

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
np.zeros_like([[1,2,3],[4,2,2]])# 创建和给定数组一样的全0数组

array([[0, 0, 0],
       [0, 0, 0]])

# 全1数列

In [43]:
np.ones((1,))

array([1.])

In [45]:
np.ones([1,2])

array([[1., 1.]])