In [1]:
import numpy as np 

# 随机函数

NumPy中也有自己的随机函数，包含在random模块中。它能产生特定分布的随机数，如正态分布等。接下来介绍一些常用的随机数。


| 函数名                          | 功能                    | 参数使用(int a,b,c,d)       |
| :------------------------------- | :----------------------- | :--------------------------- |
| rand(int1,[int2,[int3,]])       | 生成(0,1)均匀分布随机数 | (a)，(a,b)，(a,b,c)         |
| randn(int1,[int2,[int3,]])      | 生成标准正态分布随机数  | (a)，(a,b)，(a,b,c)         |
| randint(low[,hight,size,dtype]) | 生成随机整数            | (a,b)，(a,b,c)，(a,b,(c,d)) |
| sample(size)             | 生成[0,1)随机数         | (a)，((a,b))，((a,b,c))     |

### numpy.random.rand(d0,d1,…,dn)

- rand函数根据给定维度生成[0,1)之间的数据，包含0，不包含1
- dn表示每个维度
- 返回值为指定维度的array


In [4]:
np.random.rand(4,2)

array([[0.8916814 , 0.82983386],
       [0.99349204, 0.19905183],
       [0.44895569, 0.10960384],
       [0.99641623, 0.80827232]])

In [6]:
np.random.rand(4,2,3)

array([[[0.31851014, 0.17864176, 0.64696457],
        [0.98825147, 0.17569841, 0.11831557]],

       [[0.02882153, 0.35156704, 0.68622225],
        [0.09937469, 0.29828002, 0.45378156]],

       [[0.59087513, 0.56488026, 0.03916272],
        [0.6994106 , 0.68503343, 0.02260048]],

       [[0.27195343, 0.82070276, 0.44263809],
        [0.24442869, 0.12246268, 0.88387279]]])

### numpy.random.randn(d0,d1,…,dn)

- randn函数返回一个或一组样本，具有标准正态分布。
- dn表示每个维度
- 返回值为指定维度的array

标准正态分布又称为u分布，是以0为均值、以1为标准差的正态分布，记为N（0，1）。

In [8]:
np.random.randn(10)

array([-0.96134371, -1.95589203, -1.80924755,  1.09741513, -0.8837933 ,
       -0.92821513, -1.72446861, -0.15682335,  1.84165107, -0.61984692])

### numpy.random.normal()

可以实现自定义的正态分布<br>
`numpy.random.normal(loc=0.0, scale=1.0, size=None)`
作用：返回一个由size指定形状的数组，数组中的值服从 μ=loc,σ=scale 的正态分布。

参数：
- loc : float型或者float型的类数组对象，指定均值 μ
- scale : float型或者float型的类数组对象，指定标准差 σ
- size : int型或者int型的元组，指定了数组的形状。如果不提供size，且loc和scale为标量（不是类数组对象），则返回一个服从该分布的随机数。

In [40]:
np.random.normal(loc=0,scale=1,size=(6)) # 指定的形状只能是一维的

array([-0.3641015 , -0.94484693, -0.95334579,  0.25112819,  0.3033981 ,
       -1.25664386])

In [41]:
np.random.normal(loc=10,scale=2)# 不指定size返回服从该分布的一个随机数

11.390547336474938

### numpy.random.randint()

`numpy.random.randint(low, high=None, size=None, dtype=’l’)`
- 返回随机整数，范围区间为[low,high），包含low，不包含high
- 参数：low为最小值，high为最大值，size为数组维度大小，dtype为数据类型，默认的数据类型是np.int
- high没有填写时，默认生成随机数的范围是[0，low)

In [24]:
np.random.randint(1,5,size=6)# size不指定的话默认为1

array([4, 4, 4, 1, 4, 4])

In [28]:
np.random.randint(5,size=6)

array([4, 4, 1, 0, 2, 1])

In [30]:
np.random.randint(1,10,(2,3))

array([[8, 7, 7],
       [7, 8, 7]])

### numpy.random.sample

`numpy.random.sample(size=None)`

返回半开区间内的随机浮点数[0.0，1.0]。

In [33]:
np.random.sample((2,3))

array([[0.36264005, 0.26821707, 0.55521029],
       [0.24765386, 0.65415067, 0.55817096]])

### 随机种子np.random.seed()

使用相同的seed()值，则每次生成的随机数都相同,使得随机数可以预测

但是，只在调用的时候seed()一下并不能使生成的随机数相同，需要每次调用都seed()一下，表示种子相同，从而生成的随机数相同。

In [39]:
# 给定随机数种子，后面生成的随机数均相同
np.random.seed(10)
print(np.random.sample((2,3)))
print(np.random.sample((2,3)))

# 取消给定随机数种子，后面生成的随机数则不同
np.random.seed()
print(np.random.sample((2,3)))
print(np.random.sample((2,3)))

[[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]]
[[0.19806286 0.76053071 0.16911084]
 [0.08833981 0.68535982 0.95339335]]
[[0.29857415 0.76092848 0.76612717]
 [0.31257211 0.62749584 0.8634613 ]]
[[0.53349362 0.0758845  0.72842567]
 [0.522535   0.85739085 0.12174704]]
