In [1]:
import numpy as np


# 数组的其他函数

主要有以下方法:

| 函数名称 | 描述说明                                                     |
| :-------- | :------------------------------------------------------------ |
| resize   | 返回指定形状的新数组。                                       |
| append   | 将元素值添加到数组的末尾。                                   |
| insert   | 沿规定的轴将元素值插入到指定的元素前。                       |
| delete   | 删掉某个轴上的子数组，并返回删除后的新数组。                 |
| argwhere | 返回数组内符合条件的元素的索引值。                           |
| unique   | 用于删除数组中重复的元素，并按元素值由大到小返回一个新数组。 |
| sort()   | 对输入数组执行排序，并返回一个数组副本                       |
| argsort  | 沿着指定的轴，对输入数组的元素值进行排序，并返回排序后的元素索引数组 |

#### numpy.resize()

`numpy.resize(arr, shape)`

numpy.resize() 返回指定形状的新数组。

numpy.resize(arr,shape) 和ndarray.resize(shape, refcheck=False)区别:
- numpy.resize(arr,shape),有返回值,返回复制内容.如果维度不够,会使用原数组数据补齐
- ndarray.resize(shape, refcheck=False),修改原数组,不会返回数据,如果维度不够,会使用0补齐

### numpy.append()
在数组的末尾添加值，默认返回一个一维数组。

`numpy.append(arr, values, axis=None)`

参数说明：

- arr：输入的数组；
- values：向 arr 数组中添加的值，需要和 arr 数组的形状保持一致；
- axis：默认为 None，返回的是一维数组；当 axis =0 时，追加的值会被添加到行，而列数保持不变，若 axis=1 则与其恰好相反。



In [2]:
a=np.arange(10).reshape((2,5))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
np.append(a,2)# 不指定axis的时候，会把原来的数组转换成以为一维,然后加到组后

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 2])

In [35]:
a=np.arange(10).reshape((2,5))
data=np.arange(5)
print(data)

# 当指定axis参数的时候维度和原来保持一致

# 0表示第0个轴，在二位中也就是行轴。列的纬度要保持一致
print(np.append(a,[data],axis=0))

[0 1 2 3 4]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]]


In [40]:
print(a)
# 行的纬度要保持一致
print(np.append(a,[[0,1,2,3],[1,2,3,4]],axis=1))# 返回一个新的数组

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 0 1 2 3]
 [5 6 7 8 9 1 2 3 4]]


#### numpy.insert()
表示沿指定的轴，在给定索引值的前一个位置插入相应的值，如果没有提供轴，则输入数组被展开为一维数组。

`numpy.insert(arr, obj, values, axis)`

参数说明：

- arr：要输入的数组
- obj：表示索引值，在该索引值之前插入 values 值；
- values：要插入的值；
- axis：指定的轴，如果未提供，则输入数组会被展开为一维数组。


In [43]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [45]:
np.insert(a,3,888) # 展开成一维数组，在指定的索引前面进行添加

array([  1,   2,   3, 888,   4,   5,   6])

In [47]:
np.insert(a,1,[11,12])

array([ 1, 11, 12,  2,  3,  4,  5,  6])

In [50]:
np.insert(a,1,11,axis=1) # 在列的方向上进行添加，使用给定的数据进行填充,此时纬度要么是1，要么必须和原来一致

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

In [53]:
np.insert(a,1,[11,12,12],axis=1)

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 12,  6]])

In [56]:
np.insert(a,1,[[11,12,12],[2,22,2]],axis=1) # 基于广播机制 

array([[ 1, 11,  2,  2],
       [ 3, 12, 22,  4],
       [ 5, 12,  2,  6]])

#### numpy.delete()
该方法表示从输入数组中删除指定的子数组，并返回一个新数组。它与 insert() 函数相似，若不提供 axis 参数，则输入数组被展开为一维数组。
`numpy.delete(arr, obj, axis)`
参数说明：

- arr：要输入的数组；
- obj：整数或者整数数组，表示要被删除数组元素或者子数组；
- axis：沿着哪条轴删除子数组。


In [60]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [59]:
np.delete(a,2)# 删除第三个元素

array([1, 2, 4, 5, 6])

In [62]:
np.delete(a,1,axis=1)# 删除第一列

array([[1],
       [3],
       [5]])

In [64]:
np.delete(a,2,axis=0)# 删除第三行

array([[1, 2],
       [3, 4]])

In [67]:

np.delete(a,[0,1],axis=0)# 删除多行

array([[5, 6]])

#### 其他操作

In [70]:
a=np.s_[1:4]
b=np.r_[1:5]
c=np.c_[1:4]
print(a)
print(b)
# 从一到的5的一列元素
print(c)

print(np.arange(5).reshape(5,1))

slice(1, 4, None)
[1 2 3 4]
[[1]
 [2]
 [3]]
[[0]
 [1]
 [2]
 [3]
 [4]]


### numpy.argwhere()

该函数返回数组中非 0 元素的索引，若是多维数组则返回行、列索引组成的索引坐标。

In [79]:
x=np.arange(10).reshape((2,5))
print(x)
print(np.argwhere(x))
print("===============")


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [0 2]
 [0 3]
 [0 4]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]]


In [82]:
print(x[x>2])# 布尔索引
print(np.argwhere(x>2))# 大于2的索引坐标

[3 4 5 6 7 8 9]
[[0 3]
 [0 4]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]]


In [83]:
print(np.argwhere(x%2==0))

[[0 0]
 [0 2]
 [0 4]
 [1 1]
 [1 3]]


### numpy.unique()

用于删除数组中重复的元素，其语法格式如下：
`numpy.unique(arr, return_index, return_inverse, return_counts)`

参数说明：

- arr：输入数组，若是多维数组则以一维数组形式展开；
- return_index：如果为 True，则返回新数组元素在原数组中的位置（索引）；
- return_inverse：如果为 True，则返回原数组元素在新数组中的位置（索引）；
- return_counts：如果为 True，则返回去重后的数组元素在原数组中出现的次数。


In [86]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
print(np.unique(a))
print(a.size)

[2 5 6 7 8 9]
10


In [90]:
b = np.array([5,2,6,2,7,5,6,8,2,9]).reshape((2,5))
print(b)
print(np.unique(b))

[[5 2 6 2 7]
 [5 6 8 2 9]]
[2 5 6 7 8 9]


In [94]:
temp=np.unique(b,return_index=True)# 返回新数组的中的元素原来数组中的位置
print(temp)
print()
print(type(temp))

(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 4, 7, 9], dtype=int64))

<class 'tuple'>


In [96]:
temp1=np.unique(b,return_counts=True)
print(temp1)

(array([2, 5, 6, 7, 8, 9]), array([3, 2, 2, 1, 1, 1], dtype=int64))


In [102]:
arr,counts=np.unique(b,return_counts=True)
print(arr)
print(counts)
print(np.argmax(counts))# 最大值的索引
index=np.argmax(counts)
print(f'最大出现次数的值为：{arr[index]}，最大出现次数为{ counts[index] }')

[2 5 6 7 8 9]
[3 2 2 1 1 1]
0
最大出现次数的值为：2，最大出现次数为3


#### numpy.sort()

对输入数组执行排序，并返回一个数组副本。
`numpy.sort(a, axis, kind, order)`

参数说明：

- a：要排序的数组；
- axis：沿着指定轴进行排序，如果没有指定 axis，默认在最后一个轴上排序，若 axis=0 表示按列排序，axis=1 表示按行排序；
- kind：默认为 quicksort（快速排序）；
- order：若数组设置了字段，则 order 表示要排序的字段。


In [104]:
a = np.array([[3,7,5],[6,1,4]]) 
print(a)
print(np.sort(a))# 默认分别将每行进行排序

[[3 7 5]
 [6 1 4]]
[[3 5 7]
 [1 4 6]]


In [107]:
print(np.sort(a,axis=0))# 将每列进行排序

[[3 1 4]
 [6 7 5]]


In [108]:
#设置在sort函数中排序字段
dt = np.dtype([('name',  'S10'),('age',  int)])
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt) 
#再次打印a数组
print(a)
print('=='*10)# 将'=='重复10次
#按name字段排序
print(np.sort(a, order = 'name'))

[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


#### numpy.argsort()

argsort() 沿着指定的轴，对输入数组的元素值进行排序，并返回排序后的元素索引数组。示例如下： 

In [109]:
a = np.array([90, 29, 89, 12]) 
print("原数组:",a) 
sort_ind = np.argsort(a) 
print("打印排序元素索引值:",sort_ind) 

#使用索引数组对原数组排序
sort_a = a[sort_ind] 
print(sort_a)

原数组: [90 29 89 12]
打印排序元素索引值: [3 1 2 0]
[12 29 89 90]
